### ISSUE TITLE
Launch at startup

### ISSUE THREAD

**Issue by Lio1986** [Saturn-Five/RocketFuel#11]
I'm running macos 10.14.2 and I have activated "Launch at Login". However it is never launched whenever I restart my computer or logout and subsequently login. I'm using RocketFuel since July 26th, 2016 and it never worked since then.

**Comment by pkrll** [comment]
This is a known bug, and I have not found the cause of it, unfortunately.

Try to do the following:

* Uninstall the app
* Remove the folders ``com.ardalansamimi.RocketFuel`` and ``com.ardalansamimi.RocketFuelHelper`` in ``~/Library⁩/⁨Containers⁩/``
* Reboot your system
* Re-install the app
* Enable launch at login
* Reboot and see if it works

On new updates, you may also need to re-enable launch at login, that is, de-selecting launch at login and selecting it again.

Hope this helps, keep me posted!

**Comment by pkrll** [comment]
@Lio1986 Did you try the above solution?
